<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLiQuanCaPhe" Class="LionQuanLyQuanCaPheDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADMIN\HOANGKHANG;Initial Catalog=QuanLiQuanCaPhe;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DuAn1Lion.Properties.Settings" SettingsPropertyName="QuanLiQuanCaPheConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayXuatHoaDon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongHoaDon" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="SoLuongMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="HoaDon_HoaDonChiTiet" Member="HoaDonChiTiets" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="HoaDonChiTiet" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonChiTiet" Member="HoaDonChiTiets">
    <Type Name="HoaDonChiTiet">
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongTungMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDon_HoaDonChiTiet" Member="HoaDon" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="HoaDon" IsForeignKey="true" />
      <Association Name="SanPham_HoaDonChiTiet" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="HoaDon" />
      <Association Name="NhanVien_KhachHang" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguyenLieu" Member="NguyenLieus">
    <Type Name="NguyenLieu">
      <Column Name="MaNguyenLieu" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TenNguyenLieu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="ThanhPhan" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="NhaSanXuat" Type="System.String" DbType="NVarChar(125)" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhanVien_NguyenLieu" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaVaiTro" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NgayBatDauLamViec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="HoaDon" />
      <Association Name="NhanVien_KhachHang" Member="KhachHangs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="KhachHang" />
      <Association Name="NhanVien_NguyenLieu" Member="NguyenLieus" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NguyenLieu" />
      <Association Name="NhanVien_SanPham" Member="SanPhams" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="SanPham" />
      <Association Name="VaiTro_NhanVien" Member="VaiTro" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="SanPham_HoaDonChiTiet" Member="HoaDonChiTiets" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="HoaDonChiTiet" />
      <Association Name="NhanVien_SanPham" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VaiTro" Member="VaiTros">
    <Type Name="VaiTro">
      <Column Name="MaVaiTro" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenVaiTro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="VaiTro_NhanVien" Member="NhanViens" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="NhanVien" />
    </Type>
  </Table>
  <Function Name="dbo.ThongKeHoaDon" Method="ThongKeHoaDon">
    <ElementType Name="ThongKeHoaDonResult">
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NgayXuatHoaDon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongMon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongHoaDon" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKeKhachHang" Method="ThongKeKhachHang">
    <ElementType Name="ThongKeKhachHangResult">
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoLuongHoaDonThang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongHoaDonNam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongGiaTriThang" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="TongGiaTriNam" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKeNguyenLieu" Method="ThongKeNguyenLieu">
    <ElementType Name="ThongKeNguyenLieuResult">
      <Column Name="MaNguyenLieu" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="TenNguyenLieu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKeNhanVien" Method="ThongKeNhanVien">
    <ElementType Name="ThongKeNhanVienResult">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoLuongHoaDonTuan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongHoaDonThang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongHoaDonNam" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKeSanPham" Method="ThongKeSanPham">
    <ElementType Name="ThongKeSanPhamResult">
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="SoLuongBanRaTuan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongBanRaThang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongBanRaNam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongGiaBanRaTuan" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="TongGiaBanRaThang" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="TongGiaBanRaNam" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>