//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn1Lion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PJ;Initial Catalog=QuanLiQuanCaPhe;User ID=sa;Password=89898989;Conne" +
            "ct Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string QuanLiQuanCaPheConnectionString {
            get {
                return ((string)(this["QuanLiQuanCaPheConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-LUAN-PC08;Initial Catalog=QuanLiQuanCaPhe;Persist Security Info" +
            "=True;User ID=sa;Password=123456;TrustServerCertificate=True")]
        public string QuanLiQuanCaPheConnectionString1 {
            get {
                return ((string)(this["QuanLiQuanCaPheConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\HOANGKHANG;Initial Catalog=QuanLiQuanCaPhe;Persist Security Inf" +
            "o=True;User ID=sa;Password=hoangkhang160205;Encrypt=True;TrustServerCertificate=" +
            "True")]
        public string QuanLiQuanCaPheConnectionString2 {
            get {
                return ((string)(this["QuanLiQuanCaPheConnectionString2"]));
            }
        }
    }
}
